export const APP_CHANGE_LOADING_STATE = 'APP_CHANGE_LOADING_STATE';
export const APP_GET_CARS = 'APP_GET_CARS';
export const APP_GET_GUESTS = 'APP_GET_GUESTS';
export const APP_GET_RESIDENTS = 'APP_GET_RESIDENTS';
export const APP_GET_WHITELIST = 'APP_GET_WHITELIST';
export const APP_ADD_WHITELIST = 'APP_ADD_WHITELIST';
export const APP_REMOVE_WHITELIST = 'APP_REMOVE_WHITELIST';
export const APP_GET_COMMUNITY = 'APP_GET_COMMUNITY';
